package com.CardMaster.mapper.cpl;

import com.CardMaster.model.cpl.CardProduct;
import com.CardMaster.dto.cpl.request.CardProductCreateRequest;
import com.CardMaster.dto.cpl.request.CardProductUpdateRequest;
import com.CardMaster.dto.cpl.response.CardProductResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface CardProductMapper {

    // CREATE DTO -> ENTITY (productId generated by DB)
    @Mapping(target = "productId", ignore = true)
    CardProduct toEntity(CardProductCreateRequest dto);

    // UPDATE DTO -> ENTITY (DTO carries productId)
    @Mapping(target = "productId", ignore = true)
    CardProduct toEntity(CardProductUpdateRequest dto);

    // ENTITY -> RESPONSE DTO
    CardProductResponse toResponse(CardProduct entity);

    List<CardProductResponse> toResponses(List<CardProduct> entities);
}
